"""
Build the Chapter 15 per-question-type difficulty figure.

Output: Report/figures/fig_rq1_difficulty_slopes.{pdf,png}

Two side-by-side panels, shared Recall@10 (test, n=222) y-axis.

Left -- degradation by number of relevant (gold) articles
    A slope line per system across four difficulty bins:
        1  |  2-4  |  5-7  |  8+      (gold-article count)
    Steeper drop = more brittle as queries require more articles.

    These bins need PER-QUERY data (each query's gold count to assign its bin,
    and its Recall@10 to average within the bin). All six representatives have a
    recoverable full-222 per-query ranking:
        T1    bm25_tuned        (top-100 cache: output/cache/bm25_tuned_top100_test.json)
        T2    dense_me5_large   (top-100 cache: output/cache/dense_me5_large_concat2x_top100_test.json,
                                 regenerated by build_dense_perquery_cache.py)
        T3    hybrid_rrf_k60    (record _trec_run)
        T4.0  llm_rerank_top50  (record _trec_run)
        T4.1  crag_hybrid_v2    (record _trec_run)
        T4.2  react_hybrid_v2   (record _trec_run)
    The recomputed bins reconcile exactly with each system's stored aggregates:
    bin "1" equals the single_article stratum and the 2-4/5-7/8+ pool equals
    multi_article. If the dense cache is absent the dense line is skipped with a
    warning (run build_dense_perquery_cache.py to create it).

Right -- by query/article lexical overlap
    Grouped bars, two groups (lexically aligned vs semantically paraphrased),
    one bar per system in locked colour. All six tier representatives appear
    (these strata are aggregated over the full 222 for every system). The gap
    between a system's two bars is its lexical brittleness: BM25 collapses on
    paraphrased queries, dense narrows the gap, hybrid holds the top on aligned.

Usage:
  python analysis/Report_Tables_Figures/scripts/build_headline_difficulty_slopes.py
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Patch

REPORT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPORT_DIR))

from load_results import RESULTS_DIR, load_records  # noqa: E402
from thesis_style import SYSTEMS, rcparams_report, save_figure  # noqa: E402

OUTPUT_NAME = "fig_rq1_difficulty_slopes"

# Legend / colour order: all six tier representatives, top-down by tier.
ALL_SYSTEMS = [
    "bm25_tuned",
    "dense_me5_large",
    "hybrid_rrf_k60",
    "llm_rerank_top50",
    "crag_hybrid_v2",
    "react_hybrid_v2",
]
# Left panel: every tier representative, binned from its full-222 per-query
# ranking. Hybrid + agentic carry a TREC run in their record; BM25-tuned and
# dense read their per-query top-100 from a side cache (see CACHE_RANKING). The
# dense cache is regenerated by build_dense_perquery_cache.py (it re-encodes the
# 222 queries with e5-large against the cached corpus embeddings); if that cache
# is absent the dense line is skipped with a warning rather than failing.
LEFT_SYSTEMS = ["bm25_tuned", "dense_me5_large", "hybrid_rrf_k60",
                "llm_rerank_top50", "crag_hybrid_v2", "react_hybrid_v2"]

# Systems whose per-query ranking lives in a side cache rather than the record's
# _trec_run, mapping system key -> cache filename under <data_root>/cache/.
CACHE_RANKING = {
    "bm25_tuned": "bm25_tuned_top100_test.json",
    "dense_me5_large": "dense_me5_large_concat2x_top100_test.json",
}
CACHE_DIR = RESULTS_DIR.parent / "cache"

# n_gold difficulty bins (left panel).
BIN_LABELS = ["1", "2–4", "5–7", "8+"]


def _ngold_bin(n: int) -> str:
    if n == 1:
        return "1"
    if n <= 4:
        return "2–4"
    if n <= 7:
        return "5–7"
    return "8+"


def _test_qrels(recs_by_rid: dict, rid_of: dict) -> dict[str, set[str]]:
    """Per-query gold article ids (the test qrels, identical across systems)."""
    for key in ("hybrid_rrf_k60", "llm_rerank_top50", "crag_hybrid_v2", "react_hybrid_v2"):
        rec = recs_by_rid.get(rid_of[key])
        qr = rec.payload.get("_trec_qrels") if rec else None
        if qr:
            return {str(q): {str(d) for d in gold} for q, gold in qr.items()}
    raise SystemExit("No _trec_qrels found in any record — cannot bin by n_gold.")


def _ranking_for(key: str, rec) -> dict[str, list[str]] | None:
    """Per-query ranked article ids (best first), or None if unavailable."""
    if key in CACHE_RANKING:
        path = CACHE_DIR / CACHE_RANKING[key]
        if not path.exists():
            return None
        data = json.loads(path.read_text(encoding="utf-8"))
        return {str(q): [str(d) for d in lst] for q, lst in data.items()}
    run = rec.payload.get("_trec_run") if rec else None
    if not run:
        return None
    return {str(q): [d for d, _ in sorted(v.items(), key=lambda kv: -kv[1])]
            for q, v in run.items()}


def _recall_at_10_by_bin(ranking: dict[str, list[str]],
                         qrels: dict[str, set[str]]) -> dict[str, float]:
    """Mean Recall@10 per n_gold bin from a per-query ranking + gold."""
    per_bin: dict[str, list[float]] = defaultdict(list)
    for qid, gold in qrels.items():
        n_gold = len(gold)
        if n_gold == 0:
            continue
        top10 = set(ranking.get(qid, [])[:10])
        per_bin[_ngold_bin(n_gold)].append(len(top10 & gold) / n_gold)
    return {b: (sum(v) / len(v)) for b, v in per_bin.items() if v}


def _lexical_strata(rec) -> tuple[float | None, float | None]:
    """(aligned, paraphrased) Recall@10 from the stored stratified block."""
    strat = rec.stratified
    a = strat.get("lexically_aligned", {}).get("Recall@10")
    p = strat.get("semantically_paraphrased", {}).get("Recall@10")
    return a, p


def _draw_left(ax, recs_by_rid: dict, rid_of: dict) -> float:
    x = np.arange(len(BIN_LABELS))
    ymax = 0.0
    qrels = _test_qrels(recs_by_rid, rid_of)
    for key in LEFT_SYSTEMS:
        s = SYSTEMS[key]
        rec = recs_by_rid.get(rid_of[key])
        ranking = _ranking_for(key, rec)
        if ranking is None:
            print(f"[warn] no per-query ranking for {key!r}; skipping left-panel line")
            continue
        bins = _recall_at_10_by_bin(ranking, qrels)
        ys = [bins.get(b, float("nan")) for b in BIN_LABELS]
        ax.plot(x, ys, color=s.color, marker=s.marker, linestyle=s.linestyle,
                linewidth=1.6, markersize=6.5, markeredgewidth=0.6)
        for xi, yi in zip(x, ys):
            if yi == yi:
                ymax = max(ymax, yi)
                ax.annotate(f"{yi:.3f}", xy=(xi, yi), xytext=(0, 7),
                            textcoords="offset points", fontsize=6.5,
                            color=s.color, ha="center", va="bottom")
    ax.set_xticks(x, BIN_LABELS)
    ax.set_xlim(-0.3, len(BIN_LABELS) - 0.7)
    ax.set_xlabel("# relevant (gold) articles")
    ax.set_title("Degradation with more gold articles", fontsize=10, pad=6)
    ax.grid(axis="y", color="#DDDDDD", linewidth=0.6)
    ax.set_axisbelow(True)
    return ymax


def _draw_right(ax, recs_by_rid: dict, rid_of: dict) -> float:
    groups = ["aligned", "paraphrased"]
    gx = np.arange(len(groups))
    n = len(ALL_SYSTEMS)
    width = 0.82 / n
    ymax = 0.0
    for i, key in enumerate(ALL_SYSTEMS):
        s = SYSTEMS[key]
        rec = recs_by_rid.get(rid_of[key])
        if rec is None:
            continue
        a, p = _lexical_strata(rec)
        heights = [a if a is not None else float("nan"),
                   p if p is not None else float("nan")]
        offset = (i - (n - 1) / 2) * width
        bars = ax.bar(gx + offset, heights, width=width * 0.92,
                      color=s.color, edgecolor="white", linewidth=0.3)
        for rect, h in zip(bars, heights):
            if h == h:
                ymax = max(ymax, h)
                ax.annotate(f"{h:.3f}", xy=(rect.get_x() + rect.get_width() / 2, h),
                            xytext=(0, 2), textcoords="offset points",
                            fontsize=5.2, color=s.color, ha="center", va="bottom",
                            rotation=90)
    ax.set_xticks(gx, ["aligned", "paraphrased"])
    ax.set_xlim(-0.5, len(groups) - 0.5)
    ax.set_xlabel("Query/article lexical overlap")
    ax.set_title("Brittleness on paraphrased queries", fontsize=10, pad=6)
    ax.grid(axis="y", color="#DDDDDD", linewidth=0.6)
    ax.set_axisbelow(True)
    return ymax


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    records = load_records()
    recs_by_rid = {rec.experiment_id: rec for _t, rec in records}
    rid_of = {s.key: s.result_id for s in SYSTEMS.values()}

    rcparams_report()
    fig, (ax_l, ax_r) = plt.subplots(
        1, 2, figsize=(7.8, 4.0), sharey=True,
        gridspec_kw={"wspace": 0.16},
    )

    ymax_l = _draw_left(ax_l, recs_by_rid, rid_of)
    ymax_r = _draw_right(ax_r, recs_by_rid, rid_of)

    ymax = max(ymax_l, ymax_r)
    ax_l.set_ylim(0, ymax * 1.20)
    ax_l.set_ylabel(r"Recall@10 (test, $n=222$)")

    # Single colour legend (system = colour) covering both panels.
    handles = [Patch(facecolor=SYSTEMS[k].color, edgecolor="white",
                     label=SYSTEMS[k].display_short) for k in ALL_SYSTEMS]
    fig.legend(handles, [h.get_label() for h in handles],
               loc="center left", bbox_to_anchor=(0.84, 0.5),
               fontsize=8, handlelength=1.4, handletextpad=0.6,
               frameon=False, labelspacing=0.7, borderaxespad=0.0)

    fig.subplots_adjust(left=0.085, right=0.83, top=0.94, bottom=0.13)
    paths = save_figure(fig, OUTPUT_NAME, formats=("png",))  # PNG-only (no PDFs in repo)
    plt.close(fig)
    for p in paths:
        print(f"[done] Wrote {p.relative_to(REPORT_DIR.parent)}")


if __name__ == "__main__":
    main()
